#!/usr/bin/env bash

# Run in:
#
# $ docker run --rm -it --volume .:/home/user/ghost-android circleci/android:api-26-alpha bash

enable_safe_mode() {
    set -o errexit; set -o pipefail; set -o nounset; set -o xtrace;
    IFS=$'\n\t'
}

docker compose run --rm dev ./gradlew testDebug --warning-mode all
